openapi: 3.0.3
info:
  title: WASAText API specification
  description: |
    This OpenAPI document describes the API for a messaging web application.
  version: "0.0.1"

servers:
  - url: /api/v1
    description: Default API Endpoint (Local or deployed)
  - url: http://localhost:8080/api/v1
    description: Local development server
    
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      security: []
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        "201":
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                  # change here if you decide to use an integer
                  # or any other type of identifier
                    type: string
                    example: "abcdef012345"
        "400":
          description: The length of the name is out of range
  
  /user/name:
    put:
      tags: ["user"]
      summary: Update the user's name
      description: |
        If the user is authenticated and the name is not duplicated with others,
        the name will be changed
      operationId: setMyUserName
      requestBody:
        description: User name
        content:
          application/json:
            schema:
              type: object
              properties:
                newName:
                  type: string
                  example: Maria
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        "200":
          description: User name updated successfully
        "400":
          description: The length of the name is out of range
        "401":
          description: The user is unauthorized
        "409":
          description: The name is already exist
          
  /conversations:
    get:
      tags: ["conversations"]
      summary: Retrive conversations
      description: List all the conversations of the users, sorted reverse chronologically.
      operationId: getMyConversations
      responses:
        "200":
          description: Successfully retrieved conversation list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/conversation-info"
        "401":
          description: The user is unauthorized
        
  /conversations/{conversationId}:
    parameters:
      - name: conversationId
        in: path
        required: true
        description: this is the conversation id
        schema:
          type: integer
          description: an incremental number e.g., /1234 for each conversation 
          
    get:
      tags: ["conversations"]
      summary: Get a specific conversation
      operationId: getConversation
      responses:
        "200":
          description: Successfully retrieved the conversation
          content: 
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/message"
        "404":
          description:  conversation not found
          
  /messages:
    put:
      tags: ["message"]
      summary: Send message
      description: |
        Send a new message(text or photo) to the conversation 
        or reply an old message
      operationId: sendMessage
      requestBody:
        description: message details
        content:
          application/json:
            schema:
              type: object
              properties:
                conversationId:
                  type: integer
                content:
                  type: string
                contentType:
                  type: string
                  enum:
                    - text
                    - photo
                replytoId:
                  type: integer
                  nullable: true
      responses:
        "201":
          description: Message sent successfully
          
  /messages/{messageId}:
    parameters:
      - name: messageId
        in: path
        required: true
        description: this is the message id
        schema:
          type: integer
          description: an incremental number 
          
    delete:
      tags: ["message"]
      summary: Delete message
      description: Only the sender can choose to delete the message he sent
      operationId: deleteMessage
      responses:
        "200":
          description: The message was successfullt deleted
        "403":
          description: No permission to delete this message
        
  /messages/{messageId}/forward:
    parameters:
      - name: messageId
        in: path
        required: true
        description: this is the message id
        schema:
          type: integer
          description: an incremental number 
          
    post:
      tags: ["message"]
      summary: Forward message
      description: Forward a message to one or more other conversations
      operationId: forwardMessage
      requestBody:
        description: target conversation details
        content:
          application/json:
            schema:
              type: object
              properties:
                targetConversationIds:
                  type: array
                  items:
                    type: integer
        required: true
      responses:
        "200":
          description: Message forwarding successfully
        "404":
          description: Original message or target conversationn is not found
          
  /messages/{messageId}/reaction:
    parameters:
      - name: messageId
        in: path
        required: true
        description: this is the message id
        schema:
          type: integer
          description: an incremental number 
          
    post:
      tags: ["reaction"]
      summary: Comment message
      description: Add or update a reaction to the message
      operationId: commentMessage
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                emoticon:
                  type: string
        required: true
      responses:
        "200":
          description: Reaction updated successfully
        "404":
          description: Original message or target conversationn is not found
          
    delete:
      tags: ["reaction"]
      summary: Uncomment message
      description: Cancel the comment to the message
      operationId: uncommentMessage
      responses:
        "200":
          description: The reaction was successfullt deleted
        "404":
          description: Original message or target conversationn is not found
          
  /groups:
    post:
      tags: ["group"]
      summary: Create group
      description: Create a new group and specify the initial members
      operationId: createGroup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                initialMembers:
                  type: array
                  items:
                    type: integer
        required: true
      responses:
        "200":
          description: Create a new group successfully
          
  /groups/{groupId}/members:
    parameters:
      - name: groupId
        in: path
        required: true
        description: this is the group id
        schema:
          type: integer
          description: an incremental number 
          
    post:
      tags: ["group"]
      summary: Add to group
      description: Group members can add other users to the group 
      operationId: addToGroup
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/userIdsRequest'
        required: true
      responses:
        "200":
          description: Add user successfully
          
  /groups/{groupId}/me:
    parameters:
      - name: groupId
        in: path
        required: true
        description: this is the group id
        schema:
          type: integer
          description: an incremental number 
          
    delete:
      tags: ["group"]
      summary: Leave group
      description: The current user exits the group
      operationId: leaveGroup
      responses:
        "200":
          description: Leave the group successfully
          
  /groups/{groupId}/name:
    parameters:
      - name: groupId
        in: path
        required: true
        description: this is the group id
        schema:
          type: integer
          description: an incremental number 
          
    put:
      tags: ["group"]
      summary: Set group name
      operationId: setGroupName
      requestBody:
        description: Group name
        content:
          application/json:
            schema:
              type: object
              properties:
                newName:
                  type: string
        required: true
      responses:
        "200":
          description: Update group name successfully
        "403":
          description: No permission to access
                
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
      
  schemas:
    conversation-info:
      type: object
      properties:
        conversationId:
          type: integer
        name:
          type: string
        photoURL:
          type: string
          description: URL to the user/group photo
        isGroup: 
          type: boolean
        latestMessageTime:
          type: string
          format: date-time
        latestMessagePreview:
          type: string
        unreadCount:
          type: integer
      required:
        - id
        - name
        - isGroup
        
    reaction:
      type: object
      properties:
        reactorName: 
          type: string
        icon:
          type: string
    
    message:
      type: object
      properties:
        conversationId:
          type: integer
        senderName:
          type: string
        timeStamp:
          type: string
          format: date-time
        content:
          type: string
        contentType:
          type: string
          enum:
            - text
            - photo
        replyToId:
          type: integer
          nullable: true
        status:
          type: integer
          description: "0: Sent, 1: Received by all, 2: Read by all."
          enum:
            - 0
            - 1
            - 2
        reactions:
          type: array
          items: 
            $ref: '#/components/schemas/reaction'
      required:
        - conversationId
        - senderName
        - timeStamp
        - content
        - contentType
        - status
        
    userIdsRequest:
      type: object
      properties:
        userIds:
          type: array
          items:
            type: integer
      required: [userIds]

security:
  - bearerAuth: []
